languageCode = "en-us"
baseURL = ""
enableEmoji = "true"

title = "LinuxMisc"
theme = "light-hugo"
author = "0hax"

[Params]
  description = "Mostly stuffs related to Linux"
  email = "0hax@protonmail.com"
  github = "0hax"
  twitter = "0haxx"

  [Params.staticman]
  endpoint = "https://comments-0hax.herokuapp.com/v2/entry"
  username = "0hax"
  repository = "blog"
  branch = "master"
